#!/bin/sh

# Copyright (C) 2011  Matthias Müller-Reineke

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

set -e
set -x
pdebuild --debbuildopts "-us -uc"

INSTALLATION_TGZ=/var/cache/pbuilder/push-admin_installenv.tgz
if ! [ -s $INSTALLATION_TGZ ]
then
   pbuilder --create --basetgz $INSTALLATION_TGZ\
      --debootstrapopts --variant=minbase --distribution stable
fi
TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

tar xzf $INSTALLATION_TGZ -C $TMPDIR
cp -a run_in_chroot /var/cache/pbuilder/result/push-admin_0.1_all.deb $TMPDIR/home
# chroot $TMPDIR ./home/run_in_chroot
# compared to chroot this maintains the apt-cache:
# --preserve-buildplace?
pbuilder --execute --no-targz --buildplace $TMPDIR -- run_in_chroot
